project:
  output-dir: ../docs

format:
  html:
    theme: [sandstone, misc/custom.scss]
    backgroundcolor: white
    page-layout: full
    toc: true
    html-math-method: katex
    number-sections: true

  pdf:
    documentclass: article
    papersize: a4
    geometry:
      - margin=1in
    linestretch: 1.25
    fontfamily: times
    keep-tex: true
    number-sections: true
    colorlinks: true


csl: misc/frontiers.csl
highlight-style: github